batch_size: 1 
workers: 2
nepoch: 400
model_name: PointFT
load_model:  ./log/Pointft_cd_debug_pcn/model_pcn.pth
start_epoch: 0
num_points: 2048
work_dir: log/
flag: debug
loss: cd 
manual_seed: null
step_interval_to_print: 100
epoch_interval_to_save: 1
epoch_interval_to_val: 1

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

device: '0'
data_source: '../sweetpepper_dataset/shape_completion_challenge' 
dataset: 'iggfruit'  
save_vis: False
