DECODER:
    CR: 0.125 # channel ratio, change feature dimensions
    AUX_OUTPUTS: True # supervise intermediate layers
    HIDDEN_DIM: 256 # Transformer features dim
    NHEADS: 8
    DIM_FEEDFORWARD: 1024 # FFN hidden dim
    FEATURE_LEVELS: 3 # features at N scales
    DEC_BLOCKS: 3 # Dec_layers = 9: 3xFEATURE_LEVELS
    OFFSET_SCALING: 2.5
    ITERATIVE_TEMPLATE: True
    POS_ENC:
        MAX_FREQ: 10000
        DIMENSIONALITY: 3
        BASE: 2
